### ISSUE TITLE
基于回复进行反馈

### ISSUE THREAD

**Issue by wkl9438** [2245492326/interview_questions#2]
您的思路是ok的，另外题目中要求的是分页查询，而不是分表查询。
可以再写一版，我这边再看一下
数据是每个工作日都会有新增的，在处理数据的时候也可以注意一下这一块的处理

**Comment by 2245492326** [comment]
基于新思路，已更新第二题代码，现查询时间为1-2秒；
请查收

**Comment by 2245492326** [comment]
希望能得到反馈；如果有问题，希望您也能告知以提升自己

**Comment by wkl9438** [comment]
> 基于新思路，已更新第二题代码，现查询时间为1-2秒； 请查收
很抱歉，可能是我之前的描述不够清楚，基金虽然只有一万多个，但是每一个基金每一个工作日都会有一条数据，这样的话，整个数据表中数据量级会超过千万，在这种数据量级下sql查询会变得更慢。
可以采用之前提到的第二个思路，先定时去计算比率，将计算好的比率存放到内存中，这样去查询的时候只需要查询内存中的数据即可，而不用频繁查询数据库，这样可以节省很多查询数据库的时间
分页查询的话，也只需要从内存中查询出来全部数据，然后按照排序字段进行排序，再按照分页参数截取对应的数据进行返回
由于数据是每日新增的，定时任务的设置可以考虑设置为每小时，或者每几个小时更新一次，这样也可以保证数据更新的及时性
可以基于这次的反馈再次修改一次，我这边再看下。
有什么疑问，也可以询问我

**Comment by 2245492326** [comment]
您的意思是，设置定时任务：每隔几个小时就查询一次全部数据存到java里，然后在java中处理数据然后存到内存中，给前端吗
我采用这种方式是因为，单单将数据库内容全部读取到，内存中就要8秒多，没有满足您上次说的3秒内的查询需求。

**Comment by wkl9438** [comment]
> 您的意思是，设置定时任务：每隔几个小时就查询一次全部数据存到java里，然后在java中处理数据然后存到内存中，给前端吗 我采用这种方式是因为，单单将数据库内容全部读取到，内存中就要8秒多，没有满足您上次说的3秒内的查询需求。

读取数据和查询是分开的，你也不用读取全部数据到java中，你只需要把处理好得数据存到内存中就行，定时任务处理数据存到内存，存到内存中以后，查询是从内存去取，在查询这一层面上，数据来源是内存，不需要再取查数据库
也就是说这里分成两部分1：定时任务处理数据，存到内存中，定时任务定时更新存在内存中得数据
2：查询从内存中取数据，不再涉及数据库
定时任务可能会耗时较长，但是查询时从内存中查询，时间会很短
比如说我每天早上6点定时处理一次数据，将处理好得数据更新到内存中，那么我这一天中调用查询接口，取数据都是从内存中取，而不用再去查询数据库,
我所说的这个内存，你也可以理解为缓存

**Comment by 2245492326** [comment]
已更新,现在查询时间为4ms左右, 查询数据库会在服务开启时执行一次,并间隔1小时执行一次。请查收
希望能得到反馈；如果有问题，希望您也能告知以提升自己

**Comment by 2245492326** [comment]
您觉得更新后的代码怎么样呢，达到您所说的效果了吗

**Comment by 2245492326** [comment]
> > 您的意思是，设置定时任务：每隔几个小时就查询一次全部数据存到java里，然后在java中处理数据然后存到内存中，给前端吗 我采用这种方式是因为，单单将数据库内容全部读取到，内存中就要8秒多，没有满足您上次说的3秒内的查询需求。
> 
> 读取数据和查询是分开的，你也不用读取全部数据到java中，你只需要把处理好得数据存到内存中就行，定时任务处理数据存到内存，存到内存中以后，查询是从内存去取，在查询这一层面上，数据来源是内存，不需要再取查数据库 也就是说这里分成两部分1：定时任务处理数据，存到内存中，定时任务定时更新存在内存中得数据 2：查询从内存中取数据，不再涉及数据库 定时任务可能会耗时较长，但是查询时从内存中查询，时间会很短 比如说我每天早上6点定时处理一次数据，将处理好得数据更新到内存中，那么我这一天中调用查询接口，取数据都是从内存中取，而不用再去查询数据库, 我所说的这个内存，你也可以理解为缓存

您觉得更新后的代码怎么样呢，达到您所说的效果了吗

**Comment by 2245492326** [comment]
更新点是，设置定时任务读取数据库的值并计算出所需的比率，然后将计算结果保存到@bean中交由spring管理，每次前端访问数据，后台只从bean中读取数据并分页，不再查询数据库

**Comment by 2245492326** [comment]
您好，我想问一个问题，我发现将这个数据处理的过程从JAVA中处理变为从MySQL以视图的方式处理，再查询到内存中，速度会快一些。从JAVA查询处理需要7秒，查询视图只需要1秒左右。
**实际开发中推荐用哪种方式来处理呢**

java大概逻辑，项目git已更新
![Snipaste_2023-09-26_16-06-13](https://github.com/2245492326/interview_questions/assets/80482879/08f37887-5c8e-4b7f-a6cd-53d273ffa59f)
视图
![视图](https://img1.imgtp.com/2023/09/26/5bVmtNYx.png)

**Comment by 2245492326** [comment]
> > 您的意思是，设置定时任务：每隔几个小时就查询一次全部数据存到java里，然后在java中处理数据然后存到内存中，给前端吗 我采用这种方式是因为，单单将数据库内容全部读取到，内存中就要8秒多，没有满足您上次说的3秒内的查询需求。
> 
> 读取数据和查询是分开的，你也不用读取全部数据到java中，你只需要把处理好得数据存到内存中就行，定时任务处理数据存到内存，存到内存中以后，查询是从内存去取，在查询这一层面上，数据来源是内存，不需要再取查数据库 也就是说这里分成两部分1：定时任务处理数据，存到内存中，定时任务定时更新存在内存中得数据 2：查询从内存中取数据，不再涉及数据库 定时任务可能会耗时较长，但是查询时从内存中查询，时间会很短 比如说我每天早上6点定时处理一次数据，将处理好得数据更新到内存中，那么我这一天中调用查询接口，取数据都是从内存中取，而不用再去查询数据库, 我所说的这个内存，你也可以理解为缓存

您好，我想问一个问题，我发现将这个数据处理的过程从JAVA中处理变为从MySQL以视图的方式处理，再查询到内存中，速度会快一些。从JAVA查询处理需要7秒，查询视图只需要1秒左右。
**实际开发中推荐用哪种方式来处理呢**

java大概逻辑，项目git已更新
![Snipaste_2023-09-26_16-06-13](https://github.com/2245492326/interview_questions/assets/80482879/08f37887-5c8e-4b7f-a6cd-53d273ffa59f)
视图
![视图](https://img1.imgtp.com/2023/09/26/5bVmtNYx.png)

**Comment by wkl9438** [comment]
> > > 您的意思是，设置定时任务：每隔几个小时就查询一次全部数据存到java里，然后在java中处理数据然后存到内存中，给前端吗 我采用这种方式是因为，单单将数据库内容全部读取到，内存中就要8秒多，没有满足您上次说的3秒内的查询需求。
> > 
> > 
> > 读取数据和查询是分开的，你也不用读取全部数据到java中，你只需要把处理好得数据存到内存中就行，定时任务处理数据存到内存，存到内存中以后，查询是从内存去取，在查询这一层面上，数据来源是内存，不需要再取查数据库 也就是说这里分成两部分1：定时任务处理数据，存到内存中，定时任务定时更新存在内存中得数据 2：查询从内存中取数据，不再涉及数据库 定时任务可能会耗时较长，但是查询时从内存中查询，时间会很短 比如说我每天早上6点定时处理一次数据，将处理好得数据更新到内存中，那么我这一天中调用查询接口，取数据都是从内存中取，而不用再去查询数据库, 我所说的这个内存，你也可以理解为缓存
> 
> 您好，我想问一个问题，我发现将这个数据处理的过程从JAVA中处理变为从MySQL以视图的方式处理，再查询到内存中，速度会快一些。从JAVA查询处理需要7秒，查询视图只需要1秒左右。 **实际开发中推荐用哪种方式来处理呢**
> 
> java大概逻辑，项目git已更新 ![Snipaste_2023-09-26_16-06-13](https://user-images.githubusercontent.com/80482879/270583819-08f37887-5c8e-4b7f-a6cd-53d273ffa59f.png) 视图 ![视图](https://camo.githubusercontent.com/54bfbf7b6cbe2e56b77f9794ffeffca7c152c5d80ac79ca860c4175c04814ce8/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30392f32362f3562566d744e59782e706e67)

在这种情况下，要结合具体情况进行选择，一般情况下，怎么处理起来更快速就选择那种方式
但是在实际工作中，可能会遇到没有权限操作数据库的情况。
在有权限操作数据库的情况下，那种方式更快捷就是用那种即可

**Comment by 2245492326** [comment]
哦哦，好的感谢您的回答
